/*
 * blueberry.c — BlueBerryVM runtime
 *
 * Build:
 *   make blueberry
 *
 * Usage:
 *   ./blueberry <file.cbc>
 *
 * Loads and executes Citrin bytecode files produced by ./encoder.
 */



#ifndef BB_CBC_ONLY
#define BYTECODE_NO_MAIN
#define ENCODER_NO_MAIN
#include "encoder.c"
#else
#include "ciobj.c"
#endif



/* ================================================================
 *  Forward declarations & types
 * ================================================================ */

typedef struct bb_vm bb_vm;
typedef struct bb_unit bb_unit;
typedef struct bb_function bb_function;
typedef struct bb_frame bb_frame;
typedef struct bb_coro bb_coro;
typedef struct bb_closure bb_closure;
typedef struct bb_cached_op bb_cached_op;


typedef ci_ptr (*bb_op_fn)(bb_coro *c, ci_ptr a, ci_ptr b);

/* ================================================================
 *  Structs
 * ================================================================ */

struct bb_vm {
	CI_GC_HDR;
	ci_map *strings;
	ci_map *globals;
	ci_array *units;
	ci_map *proto_array;
	ci_map *proto_string;
};

struct bb_unit {
	ci_array *functions;
	uint16_t str_count;
	ci_ptr str2intern[];
};

#define bb_vm_arg  bb_vm __attribute__((unused))

typedef ci_ptr (*bb_cfn)(bb_vm *vm, ci_ptr a0, ci_ptr a1, ci_ptr a2);
typedef ci_ptr (*bb_cfn_var)(bb_vm *vm, uint8_t nargs, ci_ptr *args);

struct bb_function {
	bb_unit *unit;
	ci_ptr name;
	uint32_t flags;
	uint8_t args;
	uint8_t regs;
	uint16_t code_length;
	uint8_t *code;
	union {
		bb_cfn     cfn;
		bb_cfn_var cfn_var;
	};
};

struct bb_frame {
	bb_function *function;
	uint32_t ret_pc;
	uint32_t stack_base;
	uint8_t  ret_regs[4];
	uint8_t  ret_count;
};

/*
 * VM family — CI_O_FAMILY_8 (0x04), 8 entries for various VM object types.
 *   bb_vm       f=0x04, e0: CI_FAMILY_ENTRY(0x04, 0) = 0x04 → tag = 0x05 (+ CI_OBJECT)
 *   bb_coro     f=0x04, e1: CI_FAMILY_ENTRY(0x04, 1) = 0x0C → tag = 0x0D (+ CI_OBJECT)
 *   bb_closure  f=0x04, e2: CI_FAMILY_ENTRY(0x04, 2) = 0x14 → tag = 0x15 (+ CI_OBJECT)
 *   bb_ffistruct f=0x04, e3: CI_FAMILY_ENTRY(0x04, 3) = 0x1C → tag = 0x1D (+ CI_OBJECT)
 */
#define CI_VM_FAMILY     CI_O_FAMILY_8
#define CI_VM_TAG_BASE   CI_FAMILY_ENTRY(CI_VM_FAMILY, 0)

#define CI_BB_VM        ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 0) | CI_OBJECT | CI_REFCOUNTABLE))  /* 0x0005 */
#define CI_BB_CORO      ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 1) | CI_OBJECT | CI_REFCOUNTABLE))  /* 0x000D */
#define CI_BB_CLOSURE   ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 2) | CI_OBJECT | CI_REFCOUNTABLE))  /* 0x0015 */
#define CI_BB_FFISTRUCT ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 3) | CI_OBJECT))                    /* 0x001D */

#define CI_IS_VM_FAMILY(ptr)  CI_CHECK_MASK_FAMILY(ptr, CI_VM_FAMILY | CI_OBJECT, CI_VM_FAMILY)

// claue: similar macros for all objects
#define CI_IS_CLOSURE(ptr)  CI_CHECK_MASK_FAMILY(ptr, CI_BB_CLOSURE | CI_VM_FAMILY | CI_OBJECT, CI_VM_FAMILY)



/* #define BB_VM_DEBUG */
#ifdef BB_VM_DEBUG
#  define VM_DBG(...) printf(__VA_ARGS__)
#else
#  define VM_DBG(...) ((void)0)
#endif

#define BB_FN_NATIVE      (1u << 0)
#define BB_FN_NATIVE_VAR  (1u << 1)


#undef ci_inc
#undef ci_dec
#define ci_inc(x) ((void)(x))
#define ci_dec(x) ((void)(x))

struct bb_closure {
	CI_GC_HDR;
	bb_function *fn;
	ci_ptr self; // if not null then is generated by <- bind method
	// claude: this should have destructor that ci_dec self (decr is safe on nulls)
};

enum {
	BB_CORO_RUNNING   = (1 << 0),
	BB_CORO_SUSPENDED = (1 << 1),
	BB_CORO_DONE      = (1 << 2),
	BB_CORO_ERROR     = (1 << 3),
	BB_CORO_RETURNED  = (1 << 4)
};

struct bb_coro {
	CI_GC_HDR;
	bb_vm *vm;
	uint32_t flags;
	uint32_t pc;

	ci_array *stack;

	bb_frame *fstack;
	uint32_t fstack_pos;
	uint32_t fstack_cap;

	uint32_t lastreturn_idx;
	uint32_t lastreturn_cnt;

	ci_ptr *fast_stack;
	bb_cached_op *ops_pc;
	bb_cached_op *ops_base;
};

/* ================================================================
 *  Falsy / error
 * ================================================================ */


#define bb_error(...) do { \
	fprintf(stderr, "vm error: " __VA_ARGS__); \
	fputc('\n', stderr); \
	exit(1); \
} while(0)

__attribute__((noreturn))
static void bb_vm_error(bb_vm *vm, const char *msg) {
	(void)vm;
	fprintf(stderr, "vm error: %s\n", msg);
	exit(1);
}

/* ================================================================
 *  VM lifecycle
 * ================================================================ */

static void bb_vm_destructor(void *ptr, tg_arena_t *arena) {
	(void)arena;
	(void)ptr;
	/* TODO: teardown strings/globals/units */
}

static void bb_coro_destructor(void *ptr, tg_arena_t *arena) {
	(void)arena;
	bb_coro *c = ptr;
	free(c->fstack);
	ci_dec(c->stack);
}

static void bb_vm_types_register(void) {
	static const tg_arena_ops vm_ops   = { .destructor = bb_vm_destructor };
	static const tg_arena_ops coro_ops = { .destructor = bb_coro_destructor };
	ci_register_ops(CI_BB_VM,      sizeof(bb_vm),      &vm_ops);
	ci_register_ops(CI_BB_CORO,    sizeof(bb_coro),    &coro_ops);
	ci_register    (CI_BB_CLOSURE, sizeof(bb_closure));
}

static bb_vm *bb_vm_new(void) {
	bb_vm *vm = ci_new(CI_BB_VM);
	if (!vm)
		bb_error("bb_vm_new: out of memory");
	vm->strings = ci_map_ident_new(64);
	vm->globals = ci_map_ident_new(16);
	vm->units   = ci_arr_new(4);
	return vm;
}

static bb_closure *bb_vm_closure(bb_vm *vm, bb_function *fn) {
	bb_closure *cl = ci_new(CI_BB_CLOSURE);
	if (!cl)
		bb_vm_error(vm, "closure: out of memory");
	cl->fn = fn;
	cl->self = NULL;
	return cl;
}

static void bb_vm_free(bb_vm *vm) {
	/* TODO: proper teardown of units/functions/coros */
	(void)vm;
}

static ci_ptr bb_vm_istring(bb_vm *vm, const char *s, uint32_t len) {
	ci_str *tmp = ci_str_new(len);
	if (!tmp)
		bb_vm_error(vm, "istring: out of memory");
	ci_str_append(tmp, s, len);

	ci_ptr existing = ci_map_find(vm->strings, tmp);
	if (existing) {
		ci_dec(tmp);
		return existing;
	}

	ci_map_put(vm->strings, tmp, tmp);
	ci_nocnt(tmp);
	return tmp;
}


// calude: refactor this to
// *bb_vm_native_function(vm, name, cfn, flags)
// annd then those 2 variants are static inline calls to it

static bb_closure *bb_vm_native(bb_vm *vm, const char *name, bb_cfn cfn) {
	bb_function *fn = b_malloc(sizeof(bb_function));
	memset(fn, 0, sizeof(bb_function));
	fn->flags = BB_FN_NATIVE;
	fn->name  = bb_vm_istring(vm, name, (uint32_t)strlen(name));
	fn->cfn   = cfn;

	bb_closure *cl = ci_new(CI_BB_CLOSURE);
	if (!cl)
		bb_vm_error(vm, "native: out of memory");
	cl->fn = fn;
	return cl;
}

static bb_closure *bb_vm_native_var(bb_vm *vm, const char *name, bb_cfn_var cfn) {
	bb_function *fn = b_malloc(sizeof(bb_function));
	memset(fn, 0, sizeof(bb_function));
	fn->flags   = BB_FN_NATIVE | BB_FN_NATIVE_VAR;
	fn->name    = bb_vm_istring(vm, name, (uint32_t)strlen(name));
	fn->cfn_var = cfn;

	bb_closure *cl = ci_new(CI_BB_CLOSURE);
	if (!cl)
		bb_vm_error(vm, "native: out of memory");
	cl->fn = fn;
	return cl;
}

/* ================================================================
 *  Prototype-chain lookup
 * ================================================================ */

static ci_ptr bb_map_proto_find(bb_vm *vm, const ci_map *m, ci_ptr key) {
	(void)vm;
	for (const ci_map *cur = m; cur; cur = (const ci_map *)cur->prototype) {
		ci_ptr val = ci_map_find(cur, key);
		if (val)
			return val;
	}
	return NULL;
}

/* generic prototype lookup: NULL→null, map→proto chain, array→proto_array */
static ci_ptr bb_proto_find(bb_vm *vm, ci_ptr obj, ci_ptr key) {
	if (!obj)
		return NULL;

	if (CI_IS_MAP(obj))
		return bb_map_proto_find(vm, (const ci_map *)obj, key);

	if (CI_IS_ANY_ARR(obj)) {
		if (vm->proto_array)
			return ci_map_find(vm->proto_array, key);
		return NULL;
	}

	if (CI_IS_ANY_STR(obj)) {
		if (vm->proto_string)
			return ci_map_find(vm->proto_string, key);
		return NULL;
	}

	/* other types: no prototype yet */
	return NULL;
}

/* ================================================================
 *  Native functions
 * ================================================================ */

static void bb_print_val(ci_ptr v) {
	if (!v)
		printf("null");
	else if (CI_IS_INT(v))
		printf("%ld", CI_INT(v));
	else if (CI_IS_BOOL(v))
		printf("%s", v == CI_BOOL(1) ? "true" : "false");
	else if (CI_IS_ANY_STR(v))
		printf("%.*s", (int)ci_str_len(v), (char *)ci_str_head(v));
	else
		printf("<obj:%p>", (void *)v);
}

static ci_ptr bb_native_print(bb_vm *vm, ci_ptr a0, ci_ptr a1, ci_ptr a2) {
	(void)vm; (void)a1; (void)a2;
	bb_print_val(a0);
	printf("\n");
	return NULL;
}

static ci_ptr bb_native_setprototype(bb_vm *vm, ci_ptr a0, ci_ptr a1, ci_ptr a2) {
	(void)vm; (void)a2;
	if (!CI_IS_MAP(a0))
		bb_error("setprototype: first argument must be a map");
	if (a1 && !CI_IS_MAP(a1))
		bb_error("setprototype: second argument must be a map or null");
	ci_map *m = (ci_map *)a0;
	m->prototype = a1;
	return a0;
}


/* ================================================================
 *  Bytecode loader
 *
 *  .cbc file format (little-endian):
 *    "CIBC"              4 B  magic
 *    version             u16  = 1
 *    string_count        u16
 *    function_count      u16
 *    --- string table ---
 *    [len u16][bytes]  × string_count          (no null terminator)
 *    --- functions ---
 *    [name_idx u16][arg_count u8][reg_count u8]
 *    [local_count u16]                          (0 for now)
 *    [op_count u16]
 *    [...binary opcodes: op_count × 4 bytes...]
 *
 *  Opcode wire format — first byte: [subtype:2][opnum:6]
 *    subtype 00  RRR    [op][dst][src1][src2]   4 B
 *    subtype 01  RRU8   [op][dst][src1][imm8]   4 B
 *    subtype 10  RU16   [op][dst][imm_lo][imm_hi] 4 B (LE)
 *    subtype 11  VAR    [op][b1][extra_words][0] + extra_words × 4 B
 * ================================================================ */

#include "blueberry_vm/bytecode_load.c"

/* ================================================================
 *  Coroutine
 * ================================================================ */

static void bb_coro_pushcall(bb_coro *c, bb_function *fn) {
	if (c->fstack_pos >= c->fstack_cap)
		bb_error("frame stack overflow");

	uint32_t base = c->stack->length;

	if (!ci_arr_ensure_space(c->stack, 256))
		bb_vm_error(c->vm, "stack: out of memory");
	memset(c->stack->data + base, 0, 256 * sizeof(ci_ptr));
	c->stack->length += 256;

	bb_frame *frame   = &c->fstack[c->fstack_pos++];
	frame->function   = fn;
	frame->ret_pc     = c->pc;
	frame->stack_base = base;
}

static bb_coro *bb_coro_new(bb_vm *vm, bb_function *fn) {
	bb_coro *c = ci_new(CI_BB_CORO);
	if (!c)
		bb_vm_error(vm, "bb_coro_new: out of memory");
	c->vm    = vm;
	c->flags = 0;
	c->pc    = 0;

	c->stack = ci_arr_new(256*3);

	c->fstack_cap = 32;
	c->fstack_pos = 0;
	c->fstack     = b_malloc(c->fstack_cap * sizeof(bb_frame));

	bb_coro_pushcall(c, fn);
	return c;
}

/* ================================================================
 *  Opcode handlers
 * ================================================================ */

#include "blueberry_vm/api.c"
#include "blueberry_vm/proto_array.c"
#include "blueberry_vm/proto_string.c"
#include "blueberry_vm/opcodes.c"





/* ================================================================
 *  Dump — reuses encoder.c decode pattern for roundtrip verification
 * ================================================================ */

#include "blueberry_vm/dump.c"

/* ================================================================
 *  Execute — non-recursive, loop-based
 * ================================================================ */


/* ================================================================
 *  Fast dispatch — precached {fnptr, ctx} array
 * ================================================================ */

typedef size_t vm_dipatch_arg;

typedef __attribute__((preserve_none)) void (*bb_fast_fn)(bb_coro *co, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg c);

struct bb_cached_op {
	bb_fast_fn fn;
	vm_dipatch_arg a;
	vm_dipatch_arg b;
	vm_dipatch_arg c;
};

#include "blueberry_vm/advanced_opcodes.c"

/*
 * ctx layout (b0 stripped — fnptr already knows the op):
 *   RRR:  [d:8][a:8][b:8][0:8]
 *   RI:   [d:8][a:8][imm16:16]   — unified for both RRI8 and RI16
 *
 * During precache, RRI8 imm8 is widened to imm16 in the same slot.
 */

#define VM_OP __attribute__((preserve_none))

#define VM_OP_ACCESS_STACK       ci_ptr *sk = c->fast_stack;
#define VM_OP_STACK(idx)         sk[idx]
#define VM_OP_SET_STACK(idx, val) ci_dec(VM_OP_STACK(idx)); VM_OP_STACK(idx) = val;

#define BB_DISPATCH_NEXT(c) \
	bb_cached_op *op = c->ops_pc++;\
	[[clang::musttail]] return op->fn(c, op->a, op->b, op->c);\



#define BB_ST_RRR  (0 << 6)
#define BB_ST_RRI  (1 << 6)
#define BB_ST_RRS  (2 << 6)
#define BB_ST_VAR  (3 << 6)

#define VM_FAST_RRR(label, impl) \
VM_OP static void __vmop_##label##_rrr(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) { \
	VM_OP_ACCESS_STACK; \
	ci_ptr arg_b = VM_OP_STACK(b); \
	ci_ptr arg_c = VM_OP_STACK(_c); \
	ci_ptr r = impl(c, arg_b, arg_c); \
	ci_inc(r); \
	VM_OP_SET_STACK(a, r); \
	BB_DISPATCH_NEXT(c);\
}

#define VM_FAST_RRI(label, impl) \
VM_OP static void __vmop_##label##_rri(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) { \
	VM_OP_ACCESS_STACK; \
	ci_ptr arg_b = VM_OP_STACK(b); \
	ci_ptr arg_imm = CI_PACKINT((int32_t)_c); \
	ci_ptr r = impl(c, arg_b, arg_imm); \
	ci_inc(r); \
	VM_OP_SET_STACK(a, r); \
	BB_DISPATCH_NEXT(c);\
}

#define VM_FAST_RRS(label, impl) \
VM_OP static void __vmop_##label##_rrs(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) { \
	VM_OP_ACCESS_STACK; \
	ci_ptr arg_b = VM_OP_STACK(b); \
	bb_function *fn = c->fstack[c->fstack_pos - 1].function; \
	ci_ptr arg_key = fn->unit->str2intern[_c]; \
	ci_ptr r = impl(c, arg_b, arg_key); \
	ci_inc(r); \
	VM_OP_SET_STACK(a, r); \
	BB_DISPATCH_NEXT(c);\
}

#define VM_FAST_VAR(label, impl) \
VM_OP static void __vmop_##label##_var(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) { \
	impl(c, a, b, (uint8_t *)_c); \
	BB_DISPATCH_NEXT(c);\
}

VM_FAST_RRR(add, bb_op_add)       VM_FAST_RRI(add, bb_op_add)
VM_FAST_RRR(sub, bb_op_sub)       VM_FAST_RRI(sub, bb_op_sub)
VM_FAST_RRR(mul, bb_op_mul)       VM_FAST_RRI(mul, bb_op_mul)
VM_FAST_RRR(div, bb_op_div)       VM_FAST_RRI(div, bb_op_div)
VM_FAST_RRR(mod, bb_op_mod)       VM_FAST_RRI(mod, bb_op_mod)
VM_FAST_RRR(pow, bb_op_pow)       VM_FAST_RRI(pow, bb_op_pow)
VM_FAST_RRR(neg, bb_op_neg)
VM_FAST_RRR(op_not, bb_op_not)
VM_FAST_RRR(bin_inv, bb_op_bin_inv)
VM_FAST_RRR(bin_or, bb_op_bin_or)       VM_FAST_RRI(bin_or, bb_op_bin_or)
VM_FAST_RRR(bin_and, bb_op_bin_and)     VM_FAST_RRI(bin_and, bb_op_bin_and)
VM_FAST_RRR(bin_xor, bb_op_bin_xor)     VM_FAST_RRI(bin_xor, bb_op_bin_xor)
VM_FAST_RRR(bin_lshift, bb_op_bin_lshift) VM_FAST_RRI(bin_lshift, bb_op_bin_lshift)
VM_FAST_RRR(bin_rshift, bb_op_bin_rshift) VM_FAST_RRI(bin_rshift, bb_op_bin_rshift)
VM_FAST_RRR(eq, bb_op_eq)         VM_FAST_RRI(eq, bb_op_eq)
VM_FAST_RRR(neq, bb_op_neq)       VM_FAST_RRI(neq, bb_op_neq)
VM_FAST_RRR(gt, bb_op_gt)         VM_FAST_RRI(gt, bb_op_gt)
VM_FAST_RRR(lt, bb_op_lt)         VM_FAST_RRI(lt, bb_op_lt)
VM_FAST_RRR(gt_eq, bb_op_gt_eq)   VM_FAST_RRI(gt_eq, bb_op_gt_eq)
VM_FAST_RRR(lt_eq, bb_op_lt_eq)   VM_FAST_RRI(lt_eq, bb_op_lt_eq)
VM_FAST_RRR(notnull, bb_op_notnull)
VM_FAST_RRR(move, bb_op_move)
VM_FAST_RRR(hashaccess, bb_op_hashaccess_rrr)  VM_FAST_RRS(hashaccess, bb_op_hashaccess_rrr)
VM_FAST_RRR(mapaccess, bb_op_mapaccess)
VM_FAST_RRR(arraccess, bb_op_arraccess)
VM_FAST_RRR(methodbind, bb_op_methodbind)
VM_FAST_RRR(loadtrue, bb_op_loadtrue)
VM_FAST_RRR(loadfalse, bb_op_loadfalse)

/* --- VAR ops --- */
VM_FAST_VAR(newmap,     bb_op_newmap_var)
VM_FAST_VAR(newarray,   bb_op_newarray_var)
VM_FAST_VAR(hashaccess, bb_op_hashaccess_var)
VM_FAST_VAR(loadnull,   bb_op_loadnull_var)
VM_FAST_VAR(vmreturn,   bb_op_return_var)
VM_FAST_VAR(call,       bb_op_call_var)

/* --- RRI-only ops (no src reg, just dst + imm32) --- */

VM_OP static void __vmop_loadint(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)b;
	VM_OP_ACCESS_STACK;
	VM_OP_SET_STACK(a, CI_PACKINT((int32_t)_c));

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_loadstr(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)b;
	VM_OP_ACCESS_STACK;
	bb_function *fn = c->fstack[c->fstack_pos - 1].function;
	VM_OP_SET_STACK(a, fn->unit->str2intern[_c]);

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_loadfn(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)b;
	VM_OP_ACCESS_STACK;
	bb_function *fn = c->fstack[c->fstack_pos - 1].function;
	bb_function *f = ci_arr_index(fn->unit->functions, _c);
	bb_closure *cl = bb_vm_closure(c->vm, f);
	VM_OP_SET_STACK(a, (ci_ptr)cl);

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_jmp(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)a;
	(void)b;
	c->ops_pc = c->ops_base + _c;

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_jmpf(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)b;
	VM_OP_ACCESS_STACK;
	if (CI_IS_FALSY(VM_OP_STACK(a)))
		c->ops_pc = c->ops_base + _c;

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_jmpt(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)b;
	VM_OP_ACCESS_STACK;
	if (!CI_IS_FALSY(VM_OP_STACK(a)))
		c->ops_pc = c->ops_base + _c;

	BB_DISPATCH_NEXT(c);
}

/* --- special / sentinel --- */

VM_OP static void __vmop_arraystore(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	VM_OP_ACCESS_STACK;
	bb_op_arraystore(c->vm, VM_OP_STACK(a), VM_OP_STACK(b), VM_OP_STACK(_c));

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_hashstore(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	VM_OP_ACCESS_STACK;
	bb_op_hashstore(c->vm, VM_OP_STACK(a), VM_OP_STACK(b), VM_OP_STACK(_c));

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_hashstore_rrs(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	VM_OP_ACCESS_STACK;
	bb_function *fn = c->fstack[c->fstack_pos - 1].function;
	ci_ptr key = fn->unit->str2intern[_c];
	bb_op_hashstore(c->vm, VM_OP_STACK(a), key, VM_OP_STACK(b));

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_nop(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)a; (void)b; (void)_c;

	BB_DISPATCH_NEXT(c);
}

VM_OP static void __vmop_exit(bb_coro *c, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg _c) {
	(void)c; (void)a; (void)b; (void)_c;
	exit(0);
	BB_DISPATCH_NEXT(c);
}

/* --- dispatch table: 256 entries indexed by raw first byte --- */

static bb_fast_fn bb_fast_table[256];

static void bb_fast_table_init(void) {
	memset(bb_fast_table, 0, sizeof(bb_fast_table));

	#define FT_RRR(op, label) bb_fast_table[BB_ST_RRR | (op)] = __vmop_##label##_rrr
	#define FT_RRI(op, label) bb_fast_table[BB_ST_RRI | (op)] = __vmop_##label##_rri
	#define FT_RRS(op, label) bb_fast_table[BB_ST_RRS | (op)] = __vmop_##label##_rrs
	#define FT_RRI_ONLY(op, label) bb_fast_table[BB_ST_RRI | (op)] = __vmop_##label
	#define FT_VAR(op, label) bb_fast_table[BB_ST_VAR | (op)] = __vmop_##label##_var

	FT_RRR(B_ADD, add);       FT_RRI(B_ADD, add);
	FT_RRR(B_SUB, sub);       FT_RRI(B_SUB, sub);
	FT_RRR(B_MUL, mul);       FT_RRI(B_MUL, mul);
	FT_RRR(B_DIV, div);       FT_RRI(B_DIV, div);
	FT_RRR(B_MOD, mod);       FT_RRI(B_MOD, mod);
	FT_RRR(B_POW, pow);       FT_RRI(B_POW, pow);
	FT_RRR(B_NEG, neg);
	FT_RRR(B_NOT, op_not);
	FT_RRR(B_BIN_INV, bin_inv);
	FT_RRR(B_BIN_OR, bin_or);       FT_RRI(B_BIN_OR, bin_or);
	FT_RRR(B_BIN_AND, bin_and);     FT_RRI(B_BIN_AND, bin_and);
	FT_RRR(B_BIN_XOR, bin_xor);     FT_RRI(B_BIN_XOR, bin_xor);
	FT_RRR(B_BIN_LSHIFT, bin_lshift); FT_RRI(B_BIN_LSHIFT, bin_lshift);
	FT_RRR(B_BIN_RSHIFT, bin_rshift); FT_RRI(B_BIN_RSHIFT, bin_rshift);
	FT_RRR(B_EQ, eq);         FT_RRI(B_EQ, eq);
	FT_RRR(B_NEQ, neq);       FT_RRI(B_NEQ, neq);
	FT_RRR(B_GT, gt);         FT_RRI(B_GT, gt);
	FT_RRR(B_LT, lt);         FT_RRI(B_LT, lt);
	FT_RRR(B_GT_EQ, gt_eq);   FT_RRI(B_GT_EQ, gt_eq);
	FT_RRR(B_LT_EQ, lt_eq);   FT_RRI(B_LT_EQ, lt_eq);
	FT_RRR(B_NOTNULL, notnull);
	FT_RRR(B_MOVE, move);
	FT_RRR(B_HASHACCESS, hashaccess);  FT_RRS(B_HASHACCESS, hashaccess);
	FT_RRR(B_MAPACCESS, mapaccess);
	FT_RRR(B_ARRACCESS, arraccess);
	FT_RRR(B_METHODBIND, methodbind);
	FT_RRR(B_LOADTRUE, loadtrue);
	FT_RRR(B_LOADFALSE, loadfalse);

	FT_RRI_ONLY(B_LOADINT, loadint);
	FT_RRI_ONLY(B_LOADSTR, loadstr);
	FT_RRI_ONLY(B_LOADFN, loadfn);
	FT_RRI_ONLY(B_JMP, jmp);
	FT_RRI_ONLY(B_JMPF, jmpf);
	FT_RRI_ONLY(B_JMPT, jmpt);

	bb_fast_table[BB_ST_RRR | B_ARRAYSTORE] = __vmop_arraystore;
	bb_fast_table[BB_ST_RRI | B_ARRAYSTORE] = __vmop_arraystore;
	bb_fast_table[BB_ST_RRR | B_HASHSTORE]  = __vmop_hashstore;
	bb_fast_table[BB_ST_RRI | B_HASHSTORE]  = __vmop_hashstore;
	bb_fast_table[BB_ST_RRS | B_HASHSTORE]  = __vmop_hashstore_rrs;

	FT_VAR(B_NEWMAP,      newmap);
	FT_VAR(B_NEWARRAY,    newarray);
	FT_VAR(B_HASHACCESS,  hashaccess);
	FT_VAR(B_LOADNULL,    loadnull);
	FT_VAR(B_RETURN,      vmreturn);
	FT_VAR(B_CALL,        call);

	#undef FT_RRR
	#undef FT_RRI
	#undef FT_RRS
	#undef FT_RRI_ONLY
	#undef FT_VAR
}

/* --- build cached ops from bytecode --- */

static bb_cached_op *bb_build_cached(bb_function *fn) {
	/* one cached_op per instruction; instructions are at least 8 bytes */
	uint32_t max_wc = fn->code_length / 8 + 1;
	bb_cached_op *ops = b_malloc((max_wc + 1) * sizeof(bb_cached_op));

	uint32_t bi = 0;   /* byte cursor into fn->code */
	uint32_t wi = 0;   /* word index into ops[]     */

	while (bi < fn->code_length) {
		uint8_t  b0      = fn->code[bi];
		uint8_t  b1      = fn->code[bi + 1];
		uint8_t  b2      = fn->code[bi + 2];
		uint8_t  b3      = fn->code[bi + 3];
		uint32_t imm     = (uint32_t)fn->code[bi+4]
		                 | ((uint32_t)fn->code[bi+5] << 8)
		                 | ((uint32_t)fn->code[bi+6] << 16)
		                 | ((uint32_t)fn->code[bi+7] << 24);
		uint8_t  subtype = b0 >> 6;

		bb_fast_fn f  = bb_fast_table[b0];
		if(!f){
			bb_error("error endoing opcode - fn not found");
		}
		ops[wi].fn    = f ? f : __vmop_nop;

		switch (subtype) {
		case 0: /* RRR: a=r1, b=r2, c=r3 */
			ops[wi].a = b1;
			ops[wi].b = b2;
			ops[wi].c = b3;
			bi += 8; wi++;
			break;
		case 1: /* RRI: a=r1, b=r2, c=imm32 */
			ops[wi].a = b1;
			ops[wi].b = b2;
			ops[wi].c = imm;
			bi += 8; wi++;
			break;
		case 2: /* RRS: a=r1, b=r2, c=sid (imm) */
			ops[wi].a = b1;
			ops[wi].b = b2;
			ops[wi].c = imm;
			bi += 8; wi++;
			break;
		case 3: { /* VAR: a=r1, b=r2, c=ptr to payload (first word after header) */
			uint8_t nwords = b3;
			ops[wi].a = b1;
			ops[wi].b = b2;
			ops[wi].c = (vm_dipatch_arg)(fn->code + bi + 8);
			bi += 8 + nwords * 4;
			wi++;
			break;
		}
		}
	}

	ops[wi].fn = __vmop_exit;
	ops[wi].a = ops[wi].b = ops[wi].c = 0;
	return ops;
}
	
	
	




static void bb_vm_execute(bb_coro *c) {
	bb_frame *frame = &c->fstack[c->fstack_pos - 1];
	bb_function *fn = frame->function;
	ci_ptr *stack   = c->stack->data + frame->stack_base;

	stack[255]    = (ci_ptr)c->vm->globals;
	c->fast_stack = stack;

	bb_cached_op *ops = bb_build_cached(fn);
	c->ops_base = ops;
	c->ops_pc   = ops;

	bb_cached_op *op = c->ops_pc++;
	
	op->fn(c, op->a, op->b, op->c);
}

static void bb_coro_resume(bb_coro *c) {
	c->flags = BB_CORO_RUNNING;
	bb_vm_execute(c);
}

/* ================================================================
 *  File I/O
 * ================================================================ */

#include "blueberry_vm/util.c"

/* ================================================================
 *  Compile .ci to .cbc
 * ================================================================ */

#ifndef BB_CBC_ONLY
#include "blueberry_vm/compile.c"
#endif

/* ================================================================
 *  Main
 * ================================================================ */

#ifndef BB_NO_MAIN
int main(int argc, char **argv) {
	if (argc < 2) {
		fprintf(stderr, "usage: blueberry [-q] <file.cbc|file.ci>\n");
		return 1;
	}

	int quiet = 0;
	int file_start = 1;
	if (argc > 2 && strcmp(argv[1], "-q") == 0) {
		quiet = 1;
		file_start = 2;
	}

	ci_init();
	ci_str_register();
	ci_arr_register();
	ci_map_register();
	bb_vm_types_register();
	bb_fast_table_init();

	for (int i = file_start; i < argc; i++) {
		const char *path = argv[i];
		uint32_t len;
		uint8_t *buf = NULL;

		/* detect extension and handle accordingly */
		const char *ext = strrchr(path, '.');
#ifndef BB_CBC_ONLY
		if (ext && strcmp(ext, ".ci") == 0) {
			/* compile .ci to bytecode */
			buf = bb_compile_ci_file(path, &len);
			if (!buf)
				continue;
		} else
#endif
		{
			/* load .cbc file directly */
			buf = bb_read_file(path, &len);
			if (!buf) {
				fprintf(stderr, "error: cannot read '%s'\n", path);
				continue;
			}
		}

		if (!quiet)
			printf("=== %s (%u bytes) ===\n\n", path, len);

		bb_vm *vm = bb_vm_new();

		/* register built-in native functions */
		{
			bb_closure *print_cl = bb_vm_native(vm, "print", bb_native_print);
			ci_map_put(vm->globals, print_cl->fn->name, (ci_ptr)print_cl);

			bb_closure *setproto_cl = bb_vm_native(vm, "setprototype", bb_native_setprototype);
			ci_map_put(vm->globals, setproto_cl->fn->name, (ci_ptr)setproto_cl);
		}

		/* init built-in prototypes */
		bb_proto_array_init(vm);
		bb_proto_string_init(vm);

		bb_unit *unit = bb_vm_loadbytecode(vm, buf, len);
		free(buf);

		if (!quiet)
			bb_dump_unit(unit);

		if (ci_arr_len(unit->functions) == 0) {
			fprintf(stderr, "error: no functions in unit\n");
			bb_vm_free(vm);
			continue;
		}

		bb_function *main_fn = (bb_function *)ci_arr_index(unit->functions, 0);
		bb_coro *c = bb_coro_new(vm, main_fn);

		if (!quiet)
			printf("\n=== execute ===\n");
		bb_coro_resume(c);
		if (!quiet)
			bb_dump_regs(c);

		bb_vm_free(vm);
	}

	ci_shutdown();
	return 0;
}
#endif /* BB_NO_MAIN */
