/* ================================================================
 *  BlueBerry VM — type definitions
 * ================================================================ */

#ifndef BLUEBERRY_H
#define BLUEBERRY_H

typedef struct bb_vm bb_vm;
typedef struct bb_unit bb_unit;
typedef struct bb_function bb_function;
typedef struct bb_frame bb_frame;
typedef struct bb_coro bb_coro;
typedef struct bb_closure bb_closure;
typedef struct bb_cached_op bb_cached_op;

typedef ci_ptr (*bb_op_fn)(bb_coro *c, ci_ptr a, ci_ptr b);
typedef void  (*bb_op_fn_ext)(bb_coro *c, ci_ptr a, ci_ptr b, ci_ptr d);
typedef size_t vm_dipatch_arg;
typedef __attribute__((preserve_none)) void (*bb_fast_fn)(bb_coro *co, vm_dipatch_arg a, vm_dipatch_arg b, vm_dipatch_arg c);

typedef ci_ptr (*bb_cfn)(bb_coro *c, ci_ptr a0, ci_ptr a1, ci_ptr a2);
typedef ci_ptr (*bb_cfn_var)(bb_coro *c, ci_ptr self, size_t nargs, ci_ptr *args);

struct bb_cached_op {
	bb_fast_fn fn;
	vm_dipatch_arg a;
	vm_dipatch_arg b;
	vm_dipatch_arg c;
};

struct bb_vm {
	CI_GC_HDR;
	ci_map *strings;
	ci_map *globals;
	ci_array *units;
	ci_map *prototypes;
	bb_coro *current_coro;
	ci_str *istr_rtmp;
};

struct bb_unit {
	ci_array *functions;
	uint16_t str_count;
	ci_ptr str2intern[];
};

#define bb_coro_arg  bb_coro __attribute__((unused))

struct bb_function {
	bb_unit *unit;
	ci_ptr name;
	uint32_t flags;
	uint8_t args;
	uint8_t regs;

	uint16_t code_length;

	bb_cached_op *ops;

	uint8_t *code;
	union {
		bb_cfn     cfn;
		bb_cfn_var cfn_var;
	};
};

struct bb_frame {
	bb_closure *closure;
	bb_cached_op *pc;
	uint32_t stack_base;
};

/* Frame stack access macros */
#define bb_coro_frame(c, n)      (&(c)->fstack[n])
#define bb_coro_frame_top(c)     bb_coro_frame(c, (c)->fstack_pos - 1)
#define bb_coro_frame_caller(c)  bb_coro_frame(c, (c)->fstack_pos - 2)


#define bb_coro_frame_function(frame) (frame->closure->fn)

enum {
	BB_CORO_RUNNABLE  = (1 << 7),
	BB_CORO_RUNNING   = (1 << 0),
	BB_CORO_NEW       = (1 << 1) | BB_CORO_RUNNABLE,
	BB_CORO_SUSPENDED = (1 << 2) | BB_CORO_RUNNABLE,
	BB_CORO_DONE      = (1 << 3) | BB_CORO_RUNNABLE,
	BB_CORO_ERROR     = (1 << 4),
	BB_CORO_RETURNED  = (1 << 5)
};

struct bb_coro {
	CI_GC_HDR;
	bb_vm *vm;
	uint32_t flags;

	ci_array *stack;

	bb_frame *fstack;
	uint32_t fstack_pos;
	uint32_t fstack_cap;

	uint32_t lastreturn_idx;
	uint32_t lastreturn_cnt;
	uint32_t stop_frame;

	ci_ptr *fast_stack;
	bb_cached_op *pc;
	bb_cached_op *ops_base;
};

struct bb_closure {
	CI_GC_HDR;
	bb_function *fn;
	ci_ptr self; // if not null then is generated by <- bind method
	// claude: this should have destructor that ci_dec self (decr is safe on nulls)
};

#define CI_VM_FAMILY     CI_O_FAMILY_8
#define CI_VM_TAG_BASE   CI_FAMILY_ENTRY(CI_VM_FAMILY, 0)

#define CI_BB_VM        ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 0) | CI_REFCOUNTABLE))  /* 0x0006 */
#define CI_BB_CORO      ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 1) | CI_REFCOUNTABLE))  /* 0x000E */
#define CI_BB_CLOSURE   ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 2) | CI_REFCOUNTABLE))  /* 0x0016 */
#define CI_BB_FFISTRUCT ((uint16_t)(CI_FAMILY_ENTRY(CI_VM_FAMILY, 3)))                    /* 0x001C */

#define CI_IS_VM_FAMILY(ptr)  CI_CHECK_MASK_FAMILY(ptr, CI_VM_FAMILY, CI_VM_FAMILY)
#define CI_IS_CORO(ptr)     CI_CHECK_MASK_FAMILY(ptr, CI_BB_CORO, CI_VM_FAMILY)
#define CI_IS_CLOSURE(ptr)  CI_CHECK_MASK_FAMILY(ptr, CI_BB_CLOSURE, CI_VM_FAMILY)

#define BB_FN_NATIVE      (1u << 0)
#define BB_FN_NATIVE_VAR  (1u << 1)
#define BB_FN_NATIVE_METHOD (1u << 2)

/* ================================================================
 *  Metaproto — ci_map subtype with inline metamethod pointers
 * ================================================================ */

#define CI_TAG_METAPROTO  CI_MAP_USER_FLAG1

#define CI_IS_MAGIC_PROTO(proto) \
	((proto) && ((ci_map *)(proto))->gc.flags & CI_TAG_METAPROTO)

typedef struct {
	ci_map map;

	bb_op_fn op_add;
	bb_op_fn op_sub;
	bb_op_fn op_mul;
	bb_op_fn op_div;

	bb_op_fn op_mod;
	bb_op_fn op_bin_and;
	bb_op_fn op_bin_or;
	bb_op_fn op_bin_xor;
	bb_op_fn op_bin_lshift;
	bb_op_fn op_bin_rshift;
	bb_op_fn op_bin_inv;
	bb_op_fn op_neg;
	bb_op_fn op_cmp;
	bb_op_fn op_tostring;

	bb_op_fn     index_get;
	bb_op_fn_ext index_set;
} bb_metaproto;

#define BB_ALWAYS_INLINE __attribute__((always_inline)) static inline

#endif /* BLUEBERRY_H */
